services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: task_management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: